name: K6 Smoke Tests

on:
  workflow_dispatch:

jobs:
  k6-smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup k6
        uses: grafana/setup-k6-action@v1

      - name: Run service smoke test
        uses: grafana/run-k6-action@v1
        with:
          path: service.js
